name: number35
favicon: null
layout_spectrum: 0.5514523864258081
typography_spectrum: 0.5082533441018313
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.2186403509695083
  lightness: 0.12987960083410144
  saturation: 0.13077139016240835
  rhythmicContrast: 0.5566367655992508
purpose: []
